"""update all tables: lazy=selectin

Revision ID: 3f97c990111f
Revises: b5e282e4e47a
Create Date: 2024-08-21 09:45:38.375160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f97c990111f'
down_revision: Union[str, None] = 'b5e282e4e47a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
