"""add is_admin to users table

Revision ID: 62ba26cfc068
Revises: 0ee8dc6dd2ba
Create Date: 2024-08-16 10:38:16.519522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ba26cfc068'
down_revision: Union[str, None] = '0ee8dc6dd2ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cart_items', ['id'])
    op.create_unique_constraint(None, 'carts', ['id'])
    op.create_unique_constraint(None, 'categories', ['id'])
    op.create_unique_constraint(None, 'products', ['id'])
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='False', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint(None, 'carts', type_='unique')
    op.drop_constraint(None, 'cart_items', type_='unique')
    # ### end Alembic commands ###
