"""update: nullable to True in some columns in the Producr table

Revision ID: b225679b6697
Revises: aa12371d6a1b
Create Date: 2024-08-21 08:35:58.674694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b225679b6697'
down_revision: Union[str, None] = 'aa12371d6a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
