"""update Product table: lazy=selectin

Revision ID: b5e282e4e47a
Revises: b47a2a605d47
Create Date: 2024-08-21 09:42:31.850049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e282e4e47a'
down_revision: Union[str, None] = 'b47a2a605d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
